server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "QArxkDscJw8ogDUNNKhwlvtbLR96CtEIgDbUzkkeN+iqXg6ucLvwU/LPkDVxHpzM"
  valid-Duration: 3600 # in seconds
  refreshable-duration: 360000 # in seconds

springdoc:
  swagger-ui:
    enabled: true

app:
  file:
    storage-dir: C:/upload
    download-prefix: http://localhost:8080/api/v1/uploads
