server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mausuper202@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

outbound:
  identity:
    client-id: "87012092113-95t28ojtick2u8rff9cijv8r87i9sp46.apps.googleusercontent.com"
    client-secret: ${CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signer-key: QArxkDscJw8ogDUNNKhwlvtbLR96CtEIgDbUzkkeN+iqXg6ucLvwU/LPkDVxHpzM
  valid-duration: 3600
  refreshable-duration: 360000

springdoc:
  swagger-ui:
    enabled: true

app:
  file:
    storage-dir: C:/upload
    download-prefix: http://localhost:8080/api/v1/uploads

gemini:
  api:
    key: "AIzaSyCgI9Z8-9rYNzo1co-h5-hfRgIS4h9xnsU"



