server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://maglev.proxy.rlwy.net:45588/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: root
    password: gUhlowiuNMAkpxBSUvvkNUpANFcrSNKU
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "QArxkDscJw8ogDUNNKhwlvtbLR96CtEIgDbUzkkeN+iqXg6ucLvwU/LPkDVxHpzM"
  valid-Duration: 3600 # in second
  refreshable-duration: 360000 # in second

springdoc:
  swagger-ui:
    enabled: true




