server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

outbound:
  identity:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION}

app:
  file:
    storage-dir: ${FILE_STORAGE_DIR}
    download-prefix: ${FILE_DOWNLOAD_PREFIX}

payos:
  client-id:
  api-key:
  checksum-key:
  api-url: https://api-merchant.payos.vn/v2/payment-requests
