server:
  port: 8080
  servlet:
    context-path: /api/v1
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

spring:
  datasource:
    url: "jdbc:mysql://maglev.proxy.rlwy.net:45588/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: root
    password: gUhlowiuNMAkpxBSUvvkNUpANFcrSNKU
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "QArxkDscJw8ogDUNNKhwlvtbLR96CtEIgDbUzkkeN+iqXg6ucLvwU/LPkDVxHpzM"
  valid-Duration: 3600 # in second
  refreshable-duration: 360000 # in second

openapi:
  service:
    api-docs: Flexistudy-Service API
    server: http://localhost:8080
    title: Flexistudy-Service API
    version: 1.0.0
springdoc:
  swagger-ui:
    enabled: true

app:
  file:
    storage-dir: C:/upload
    download-prefix: http://localhost:8080/api/v1/uploads/

